logging:
    file:
        name: /logs/sboard.log
    level:
        jdbc:
            resultsettable: debug
            sqlonly: debug
            sqltiming: debug
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                sql: debug
        root: info
server:
    port: 8080
    servlet:
        context-path: /sboard


spring:
    application:
        name: sboard
        version: 0.0.2
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://43.203.253.92:3306/jboard
        username: jboard
        password: "!Q2w3e4r"

    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

    thymeleaf:
        prefix: classpath:/templates


    servlet:
      multipart:
          location: uploads/
          max-file-size: 10MB
